wandb_version: 1

seq_length:
  desc: null
  value: 30
hidden_dim:
  desc: null
  value: 100
layer_dim:
  desc: null
  value: 1
output_dim:
  desc: null
  value: 1
criterion:
  desc: null
  value: MSELoss
optimizer:
  desc: null
  value: SGD
learning_rate:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 128
num_epochs:
  desc: null
  value: 1112
seed:
  desc: null
  value: 40
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718292408
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 3
      - 16
      - 23
      4: 3.10.14
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
